<?php echo '<'.'?'.'php'; ?>

/**
 *  this is an autogenerated bootstrap file for the Montage PHPUnit plugin
 *  
 *  @package    test
 *  @subpackage PHPUnit
 *  @author     <?php echo $this->getField('author'),PHP_EOL; ?>
 ******************************************************************************/

// include the framework...
<?php foreach($this->getField('framework_path_list',array()) as $framework_path): ?>
include_once('<?php echo $framework_path; ?>');
<?php endforeach; ?>

// create and activate the framework...
$framework = new <?php echo $this->getField('framework_class_name'); ?>(
  'test',
  '<?php echo $this->getField('app_path'); ?>'
);
$framework->preHandle();

// the autoloader should include the test paths also...
$framework->getContainer()->getAutoloader()->addPaths(
  $framework->getContainer()->getConfig()->getField('test_paths',array())
);

// set the static instance that any children can use...
\PHPUnit\FrameworkTestCase::setFramework($framework);

// get rid of any variables so PHPUnit doesn't try to save them and add them to $GLOBALS... 
unset($framework);
unset($app_path);
